# Generated by Django 2.2.3 on 2019-07-30 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='time_add',
            field=models.DateField(default=datetime.date(2019, 7, 30)),
        ),
    ]
