# Generated by Django 2.2.3 on 2019-07-31 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0002_auto_20190730_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='check',
            new_name='check_state',
        ),
        migrations.AlterField(
            model_name='annotation',
            name='time_add',
            field=models.DateField(default=datetime.date(2019, 7, 31)),
        ),
    ]
